# Generated by Django 3.2.3 on 2021-06-06 09:15

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='auth.user')),
                ('age', models.IntegerField()),
                ('phone', models.CharField(max_length=13)),
                ('address', models.CharField(max_length=300)),
                ('post', models.CharField(max_length=60)),
                ('dateofjoin', models.DateField()),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='EmpWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('your_post', models.CharField(max_length=60)),
                ('join_company_date', models.DateField()),
                ('leave_company_date', models.DateField()),
                ('empw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.emp')),
            ],
        ),
        migrations.CreateModel(
            name='EmpSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salarydate', models.DateField()),
                ('monthofsalary', models.CharField(max_length=12)),
                ('amount', models.IntegerField()),
                ('emp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp.emp')),
            ],
        ),
        migrations.CreateModel(
            name='EmpQulification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isHighSchoolGraduate', models.BooleanField(default=False)),
                ('isUndergraduate', models.BooleanField(default=False)),
                ('isCollegeGraduate', models.BooleanField(default=False)),
                ('empq', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='emp.emp')),
            ],
        ),
    ]
