# Generated by Django 3.2.3 on 2021-06-01 04:09

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0002_customer_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
                ('subject', models.CharField(max_length=300)),
                ('message', models.TextField(max_length=1000)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
