# Generated by Django 3.2.3 on 2021-06-02 07:36

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('resto', '0005_customer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(default="646472782", max_length=128, region=None),
            preserve_default=False,
        ),
    ]
